tf.maximum:用法tf.maximum(a,b),返回的是a,b之间的最大值
tf.miniimum:用法tf.miniimum(a,b),返回的是a,b之间的最小值

TensorArray可以看做是具有动态size功能的tensor数组。通常都是跟while_loop或map_fn结合使用例如：

In [33]:
import tensorflow as tf

In [34]:
def condition(time,output_ta_l):
    return tf.less(time,3)  

In [35]:
def body(time,output_ta_l):
    output_ta_l=output_ta_l.write(time,[2.4,3.5])
    return time+1,output_ta_l

In [37]:
time=tf.constant(0)
output_ta=tf.TensorArray(dtype=tf.float32,size=1,dynamic_size=True)
result =tf.while_loop(condition,body,loop_vars=[time,output_ta])
last_time,last_out=result
final_out =last_out.stack()
with tf.Session():
    print(last_time.eval())
    print(final_out.eval())

3
[[2.4 3.5]
 [2.4 3.5]
 [2.4 3.5]]


In [1]:
#例子
import tensorflow as tf
a = [1,2,3]  

f1 = tf.maximum(a, 3)  
f2 = tf.minimum(a, 3)  
f3 = tf.argmax(a, 0)  
f4 = tf.argmin(a, 0)  

with tf.Session() as sess:  
    print(sess.run(f1))#print f1.eval()  
    print(sess.run(f2)) 
    print(sess.run(f3))  
    print(sess.run(f4))

[3 3 3]
[1 2 3]
2
0
