In [36]:
#导入所需要使用的应用包
import scipy.io as sio
import numpy as np
import os
import re

In [39]:
#对数据集进行加载并为其添加，类别标签
path='./dataset/train/'
data=np.array([])
#利用数组创建一个空标签
label=[]
for file in os.listdir(path):
    key = re.sub('.mat',"",file)
    num = re.sub("\D","",file)
    data1 = sio.loadmat(path+file)[key]
    class_num = data1.shape[0]
    for _ in range(class_num):
        label.append(num)
    data = np.append(data,data1)    
data = data.reshape((-1,200)) 
label = np.array(label,dtype=np.int32)
data

array([[3693., 4256., 4503., ..., 1050., 1024., 1024.],
       [2589., 4372., 4334., ..., 1050., 1024., 1019.],
       [3693., 4128., 4507., ..., 1045., 1029., 1019.],
       ...,
       [3192., 4235., 4313., ..., 1026., 1023., 1000.],
       [3192., 4111., 4313., ..., 1030., 1014., 1008.],
       [3192., 4115., 4313., ..., 1031., 1014., 1013.]])

In [40]:
print(label)

[10 10 10 ...  8  8  8]


In [41]:
#模型的训练，构建
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
# 划分训练集和验证集
X_train,X_test,y_train,y_test= train_test_split(
        data,label,test_size=0.20,shuffle=True)  #将数据随机打乱
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [42]:
svc = SVC(C=10,gamma=0.01,class_weight='balanced')  #构建分类器，设定参数
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9285198555956679


In [43]:
# 对于测试集进行加载
test= sio.loadmat("./dataset/data_test_final.mat")['data_test_final']
test= np.array(test_data, dtype=np.float64)
print(test)

[[3158. 4122. 4145. ... 1022. 1019. 1010.]
 [3023. 3737. 4027. ... 1019. 1008. 1004.]
 [2743. 4388. 4591. ... 1056. 1030. 1025.]
 ...
 [2561. 3881. 4051. ... 1018.  998. 1015.]
 [2745. 4391. 4335. ... 1046. 1029. 1019.]
 [3009. 3986. 3967. ... 1011. 1009. 1000.]]


In [49]:
#将测试集进行标准化
x_test = scaler.transform(test)
x_test

array([[ 0.51698954, -0.15423302, -0.89352438, ..., -0.89432146,
        -0.13778634, -0.05087331],
       [ 0.16027189, -1.96057531, -1.38287967, ..., -1.03737191,
        -1.10308284, -0.91085482],
       [-0.57958692,  1.09378529,  0.95607272, ...,  0.72691704,
         0.82751017,  2.09908047],
       ...,
       [-1.06049515, -1.28495637, -1.28334978, ..., -1.0850554 ,
        -1.98062512,  0.66577795],
       [-0.57430221,  1.10786069, -0.10557943, ...,  0.25008219,
         0.73975594,  1.23909896],
       [ 0.12327895, -0.79231757, -1.63170439, ..., -1.41883979,
        -1.01532861, -1.48417583]])

In [50]:
y_test = svc.predict(x_test)
y_test

array([12,  5,  3, ..., 14, 12,  6])

In [51]:
import pandas as pd
data = pd.DataFrame(y_test)
data.to_csv("./dataset/testy.csv")